
project_id = "medzxzfdadwzpuqimeih"

[functions.chat]
verify_jwt = true

[functions.chat-history]
verify_jwt = true

[functions.check-message-limits]
verify_jwt = true

[functions.intro-chat]
verify_jwt = true

[functions.embed-conversation-chunk]
verify_jwt = true

[functions.vector-search-context]
verify_jwt = true

[functions.overseer]
verify_jwt = true

[functions.middle-thoughts]
verify_jwt = true

[functions.amorine_updater]
verify_jwt = true

[functions.pre-checker]
verify_jwt = true

[functions.amorineimages-vector]
verify_jwt = true

[functions.image-context-analyzer]
verify_jwt = true

[functions.amorine-image-search]
verify_jwt = true

