
project_id = "medzxzfdadwzpuqimeih"

[functions.chat]
verify_jwt = true

[functions.chat-history]
verify_jwt = true

[functions.check-message-limits]
verify_jwt = true

[functions.emotion-analyzer]
verify_jwt = true

[functions.chunk-summarizer]
verify_jwt = true

[functions.chunk-counter]
verify_jwt = true

[functions.super_summary_counter]
verify_jwt = true

[functions.super_summarizer]
verify_jwt = true

[functions.update-user-profile-analysis]
verify_jwt = true

[functions.intro-chat]
verify_jwt = true

[functions.validation]
verify_jwt = true

