project_id = "medzxzfdadwzpuqimeih"

[functions.chat]
verify_jwt = true

[functions.chat-history]
verify_jwt = true

[functions.check-message-limits]
verify_jwt = true

[functions.emotion-analyzer]
verify_jwt = true

[functions.chunk-summarizer]
verify_jwt = true