
project_id = "medzxzfdadwzpuqimeih"

[global.middleware.env]
UPSTASH_REDIS_REST_URL = "std"
UPSTASH_REDIS_REST_TOKEN = "std"
SUPABASE_URL = "std"
SUPABASE_SERVICE_ROLE_KEY = "std"

[http_server]
port = 54321
