
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://medzxzfdadwzpuqimeih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZHp4emZkYWR3enB1cWltZWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NTQ2ODQsImV4cCI6MjA1NDAzMDY4NH0.KJtDwdSUVs-l32_D56xL5a_ead1dRri9gxx9r923nqA";

// Create Supabase client with proper configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});

// Initialize auth state and prefetch session
const initializeAuth = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  if (session) {
    // Ensure the client has the latest session
    await supabase.auth.setSession(session);
  }
};

// Initialize auth
initializeAuth().catch(console.error);
